spring:
  profiles:
    active: ${ACTIVE_PROFILE:test}
  mail:
    host: ${MAILGUN_HOST}
    port: ${MAILGUN_PORT}
    protocol: smtp
    username: ${MAILGUN_USERNAME}
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: Send Mail